config/routes.rb
Patronhood::Application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, :path_names => { 
                        :sign_in => "login", 
                        :sign_out => "logout", 
                        :sign_up => "signup" 
                      }, 
                     :controllers => {
                        :registrations => 'custom_devise/registrations'
                     }

  devise_scope :user do 
    match "signup" => "custom_devise/registrations#new"
    match "login" => "devise/sessions#new"
    delete "logout" => "devise/sessions#destroy"
  end

  resources :beta_users, :except => [:index, :show, :update, :edit]
  match "beta_signup" => "beta_users#new", :as => :beta_signup
  match '/beta_confirmation' => 'beta_users#confirmation'

  match '/dashboard', to: 'dashboard#index'
  match '/about', to: "static_pages#about"
  match '/faq', to: "static_pages#faq"
  match '/terms', to: "static_pages#terms"
  match '/team', to: "static_pages#team"
  match '/privacy', to: "static_pages#privacy"

  resources :works, :except => :index
  match '/new_work', to: 'works#new'
  match 'works/:id/cancel' => 'works#cancel', :as => 'cancel_work'
  match 'works/:id/approve' => 'works#approve', :as => 'approve_work'

  resources :works, :except => [:index] do
    resources :patrons, :except => [:index, :show, :update, :edit], :path_names => { :new => "fund" }
    resources :work_updates, :as => 'updates', :except => [:index, :show, :update, :edit]
  end

  match '/patronage_confirmation' => 'patrons#confirmation'

  unless Rails.application.config.consider_all_requests_local
    match '*a', to: 'errors#error_404'
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @works = current_user.admin? ? Work.all : current_user.works.all
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_admin.html.haml
-# Edit Work
= link_to edit_work_path(w), :rel => "tooltip", :title => "Edit Work" do
  %i.icon-pencil

-# Preview Work
= link_to w, :rel => "tooltip", :title => "Preview Work" do
  %i.icon-eye-open
  
- if w.status == WORK_APPROVED || w.status == WORK_RUNNING
  -# Cancel Work
  = link_to cancel_work_path(w), :rel => "tooltip", :title => "Cancel Work", |
    confirm: "You are about to cancel this work. Are you sure?" do
    %i.icon-remove-circle
- else
  -# Remove the work
  = link_to w, :rel => "tooltip", :title => "Remove Work", method: :delete, |
    confirm: "You are about to delete this work. Are you sure?" do          |
    %i.icon-remove

app/views/dashboard/_cancelled.html.haml
-# Edit Work
= link_to edit_work_path(w), :rel => "tooltip", :title => "Edit Work" do
  %i.icon-pencil

-# Preview Work
= link_to w, :rel => "tooltip", :title => "Preview Work" do
  %i.icon-eye-open

-# Remove Work
= link_to w, :rel => "tooltip", :title => "Remove Work", method: :delete, |
  confirm: "You are about to delete this work. Are you sure?" do          |
  %i.icon-remove

app/views/dashboard/_running.html.haml
-# Post an update
= link_to new_work_update_path(w), :rel => "tooltip", :title => "Preview Work" do
  %i.icon-comment

-# Preview the work
= link_to w, :rel => "tooltip", :title => "Preview Work" do
  %i.icon-eye-open

-# Cancel the work
= link_to cancel_work_path(w), :rel => "tooltip", :title => "Cancel Work", | 
  confirm: "You are about to cancel this work. Are you sure?" do
  %i.icon-remove-circle

app/views/dashboard/_saved.html.haml
-# Edit the work
= link_to edit_work_path(w), :rel => "tooltip", | 
  :title => "Edit Work" do
  %i.icon-pencil

-# Preview the work
= link_to w , :rel => "tooltip", :title => "Preview Work" do
  %i.icon-eye-open

-# Remove the work
= link_to w, :rel => "tooltip", :title => "Remove Work",  | 
  method: :delete, confirm: "You are about to delete this |
  work. Are you sure?" do                                 |
  %i.icon-remove

app/views/dashboard/_submitted.html.haml
-# Preview the work
= link_to w, :rel => "tooltip", :title => "Preview Work" do
  %i.icon-eye-open

-# Remove the work
= link_to w, :rel => "tooltip", :title => "Remove Work", |
  method: :delete, confirm: "You sure?" do               |
  %i.icon-remove

app/views/dashboard/_successful.html.haml
-# Preview Work
= link_to w, :rel => "tooltip", :title => "Preview Work" do
  %i.icon-eye-open

-# Comment / Post an update 
%i.icon-comment

-# Download list of patrons and their patronage
%i.icon-download-alt

app/views/dashboard/_unsuccessful.html.haml
-# Preview Work
= link_to w, :rel => "tooltip", :title => "Preview Work" do
  %i.icon-eye-open

%i.icon-exclamation-sign

app/views/dashboard/index.html.haml
.container-background-dashboard
  .works-header
    %header#overview.jumbotron.subhead
      .header-content
        - if !current_user.admin?
          %h1 Works Dashboard
          %p.lead A list of all your works and their status
        - else
          %h1 One ring to rule them all
          %p.lead Welcome to the admin page!
.container
  .dashboard-alerts
    - flash.each do |key, msg|
      .alert.alert-block
        %p= msg
  .container-content-dashboard
    .dashboard
      - if !@works.empty?
        %table#dashboard-works.table.tablesorter
          %thead
            %tr
              %th Work
              %th Status
              %th Time Left
              %th Funded
              %th Actions
          %tbody
            - @works.each do |w|
              %tr
                %td= link_to w.name, w
                - case w.status
                - when WORK_SAVED
                  %td.work-saved.work-status Saved
                - when WORK_SUBMITTED
                  %td.work-submitted.work-status Submitted
                - when WORK_APPROVED
                  %td.work-running.work-status Approved
                - when WORK_RUNNING
                  %td.work-running.work-status Running
                - when WORK_SUCCESSFUL
                  %td.work-successful.work-status Successful
                - when WORK_UNSUCCESSFUL
                  %td.work-failed.work-status Unsuccessful
                - when WORK_CANCELLED
                  %td.work-cancelled.work-status Cancelled
                - when WORK_REJECTED
                  %td.work-rejected.work-status Rejected
                %td.work-time-na N/A
                %td.work-progress-na N/A
                %td
                  - if !current_user.admin?
                    - case w.status
                    - when WORK_SAVED
                      = render 'saved', :w => w
                    - when WORK_SUBMITTED
                      = render 'submitted', :w => w
                    - when WORK_APPROVED
                      = render 'running', :w => w
                    - when WORK_RUNNING
                      = render 'running', :w => w
                    - when WORK_SUCCESSFUL
                      = render 'successful', :w => w
                    - when WORK_UNSUCCESSFUL
                      = render 'unsuccessful', :w => w
                    - when WORK_CANCELLED
                      = render 'cancelled', :w => w
                    - when WORK_REJECTED
                      = render 'unsuccessful', :w => w
                  - else
                    = render 'admin', :w => w
      - else
        .empty-pane
          %p Seems quiet in here... *Chirp Chirp Chirp*