config/routes.rb
Patronhood::Application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, :path_names => { 
                        :sign_in => "login", 
                        :sign_out => "logout", 
                        :sign_up => "signup" 
                      }, 
                     :controllers => {
                        :registrations => 'custom_devise/registrations'
                     }

  devise_scope :user do 
    match "signup" => "custom_devise/registrations#new"
    match "login" => "devise/sessions#new"
    delete "logout" => "devise/sessions#destroy"
  end

  resources :beta_users, :except => [:index, :show, :update, :edit]
  match "beta_signup" => "beta_users#new", :as => :beta_signup
  match '/beta_confirmation' => 'beta_users#confirmation'

  match '/dashboard', to: 'dashboard#index'
  match '/about', to: "static_pages#about"
  match '/faq', to: "static_pages#faq"
  match '/terms', to: "static_pages#terms"
  match '/team', to: "static_pages#team"
  match '/privacy', to: "static_pages#privacy"

  resources :works, :except => :index
  match '/new_work', to: 'works#new'
  match 'works/:id/cancel' => 'works#cancel', :as => 'cancel_work'
  match 'works/:id/approve' => 'works#approve', :as => 'approve_work'

  resources :works, :except => [:index] do
    resources :patrons, :except => [:index, :show, :update, :edit], :path_names => { :new => "fund" }
    resources :work_updates, :as => 'updates', :except => [:index, :show, :update, :edit]
  end

  match '/patronage_confirmation' => 'patrons#confirmation'

  unless Rails.application.config.consider_all_requests_local
    match '*a', to: 'errors#error_404'
  end

end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .content-footer-block
      %ul.links
        %li
          = link_to "Log In", login_path
        %li
          = link_to "Blog", login_path
        %li
          = link_to "FAQ", faq_path
        %li
          = link_to "Terms of Use", terms_path
        %li
          = link_to "Privacy Policy", privacy_path


    .content-footer-block
      .contact-content
        %table
          %tr
            %td
              .email
            %td
              team@patronhood.com

          %tr
            %td
              .twitter
            %td
              @patronhood
      
          %tr
            %td
              .facebook
            %td
              facebook.com/patronhood

    .content-footer-block
      .quote-content
        .quote-mark
        %p
          Cities have the capability of providing something for everybody, |
          only because, and only when, they are created by everybody.      |
          %br
          %br
          %b - Jane Jacobs

      

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    / 01010000110000011101001110010110111011011101101000110111011011101100100 
    / Created By: Adrian Del Balso, Jason Lagaac & Sachin Shukla

    %title Patronhood
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?sensor=false"
    = javascript_include_tag "https://js.stripe.com/v1/", "application"
    = tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY
    = tag :meta, :name => "google-site-verification", :content => GOOGLE_SITE_VERIFICATION

    = analytics_init if Rails.env.production? 
    
  %body{"data-offset" => "50", "data-spy" => "scroll", "data-target" => ".subnav"}
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path do
            .brand
          .tagline
          .nav-collapse.collapse
            %ul.nav
              - if user_signed_in? && current_user.admin? && !@work.nil?  | 
                && current_page?(@work) && @work.status == WORK_SUBMITTED |
                %li.submit
                  = link_to "REJECT WORK", reject_work_path(@work)
                %li.submit
                  = link_to "APPROVE WORK", approve_work_path(@work)
              %li.submit
                - if current_page?(@work) && !@work.nil? && @work.status.eql?(WORK_RUNNING)
                  = link_to "FUND THIS WORK",  new_work_patron_path(@work)

                - elsif !@work.nil? && !current_user.nil? && @work.user_id.eql?(current_user.id) |
                  && params[:action] == "show" && params[:controller] == "works" &&        |
                  WORK_EDITABLE.include?(@work.status) |
                  = link_to "EDIT THIS WORK", edit_work_path(@work)

                - elsif current_page?('/new_work') || current_page?(new_work_path) || | 
                  ((params[:action] == "new" || params[:action] == "create") && |
                  params[:controller] == "works") |
                  %a#savemywork{:href => "#"} SAVE MY WORK

                - elsif !@work.nil? && (@work.status == WORK_SAVED) && (params[:action] == "edit" |
                  && params[:controller] == "works" || params[:action] == "update" && |
                  params[:controller] == "works") |
                  %a#savechanges{:href => "#"} SAVE WORK CHANGES

                - elsif @work.nil? || params[:controller] == "work_updates"
                  = link_to "SUBMIT A WORK", new_work_path

              - if !@work.nil? && params[:controller] == "patrons"
                %li.submit-back
                  = link_to "TAKE ME BACK", work_path(@work)

              %li
                = link_to "HOME", root_path

              - if !user_signed_in?
                %li
                  = link_to "FAQ", faq_path
                %li
                  %a{:href => "http://blog.patronhood.com"} BLOG
                %li
                  = link_to "LOG IN", login_path
              - else
                %li
                  = link_to "DASHBOARD", dashboard_path
                %li
                  = link_to "LOG OUT", logout_path, :method => :delete
    
    
    = yield
    
    = render "layouts/footer"

    = debug(params.inspect) if Rails.env.development?